# Generated by Django 5.2.3 on 2025-07-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PaymentDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=100)),
                ('associate_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_data.person')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=100)),
                ('associate_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_data.person')),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=100)),
                ('associate_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_data.person')),
            ],
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=100)),
                ('associate_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('payment_explanation', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_data.person')),
            ],
        ),
        migrations.CreateModel(
            name='CallingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=100)),
                ('associate_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_data.person')),
            ],
        ),
    ]
