# Generated by Django 5.2.3 on 2025-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_data', '0002_person_alter_profile_user_id_paymentdone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingsheet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interested',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentdone',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
